### ISSUE TITLE
CTRL+Space doesn't work

### ISSUE THREAD

**Issue by fracarma** [sorenkrabbe/Chrome-Salesforce-inspector#56]
On my PC (Fedora + Google Chrome) the Ctrl+Space shortcut doesn't insert anything in the exportData page. Is it normal?

**Comment by jesperkristensen** [comment]
I don't have a linux with Chrome near by to test on.
Which version of Chrome do you use?
Which version of Salesforce Inspector do you use? (the latest release, or the source from Github?)
Can you give an example of a query, and where exactly in the query the caret is placed? Maybe with a screenshot?

**Comment by fracarma** [comment]
Hello Jesper,
I have got the  46.0.2490.86 ((64-bit) Linux Chrome version. Right now I am using the GitHub latest version, but the issue is also on the Chrome extensions market one.

I have found, logging on my forked extension, that the problem in the binding of the keystroke "ctrl+space'. It seems be "intercepted" by some application running on my OS, the problem is just when the cursor is active on the textInput.

Probably the fastest workaround is to change the shortcut keys by code!

**Comment by fracarma** [comment]
Hello Jesper,
I have got the  46.0.2490.86 ((64-bit) Linux Chrome version. Right now I am using the GitHub latest version, but the issue is also on the Chrome extensions market one.

I have found, logging on my forked extension, that the problem in the binding of shortcut on the textArea. I found a way to make it work using the library "mousetrap". If I am going to fix it I will make a pull request.

Thanks!

**Comment by jesperkristensen** [comment]
I have set up a Linux VM and reproduced the issue in Chrome on Linux. I made a fix without using an external library.

There was a comment in Mousetrap saying "chrome will not fire a keypress if meta or control is down"
https://github.com/ccampbell/mousetrap/commit/2446453dfbd065d3ebfded470a8edeb08ec52c70

Unfortunately there was no reference to a Chrome bug number or the code Mousetrap used to work around it, so I tested it, and Mousetrap uses the keydown event instead of keypress. So I switched to using that, which seems to work in Chrome/Linux, Firefox/Linux, Chrome/Windows and Firefox/Windows.

I found https://code.google.com/p/chromium/issues/detail?id=527111 which uses examples with the Ctrl key, so maybe Chrome will fix this soon, and we we can update the code to use the new "key" property instead once both Chrome and Firefox support it.
