### ISSUE TITLE
Filter Show All Data to only data that is not shown on the current page

### ISSUE THREAD

**Issue by JodieM** [sorenkrabbe/Chrome-Salesforce-inspector#60]
This is a feature request, not an issue. I love this product. I was just looking at a record that was created by an API, so I didn't know the data really well. I went to View All Data and thought, I really just want to see everything that's not currently on the page, so I can see if the page layout needs updating or any random data is getting in via the API call that I was not expecting.

I'm not even sure it's technically possible.

**Comment by jesperkristensen** [comment]
Great idea. We should query the layout (which require an extra API call, but I think that is OK, since we already do a few of those), and add relevant information from it to the field properties (the ones you see when you click the "More" link on each row). If we do that, you can use it in the filter box. We can only do this if we show a specific record (as opposed to only showing object level information), since we need to know the record type to query the layout.

Somewhat related, we should make the list of available filters much more discoverable, using some kind of autocomplete in the filter box.

**Comment by JodieM** [comment]
Sounds great. Thanks Jasper.

**Comment by jesperkristensen** [comment]
Fixed in e6a336ea. It is now possible to filter on `layout.shownOnLayout=false` in the filter box. You still have to click the `More` link next to one of the rows to discover this filter option.

I plan to release a version with this fix shortly after the Spring '16 release.
