### ISSUE TITLE
revert to old version

### ISSUE THREAD

**Issue by hubsonx** [sorenkrabbe/Chrome-Salesforce-inspector#71]
Hi,

I'm using the chrome version of the plugin. Today I have update the plugin to 1.0 version and everything stopped to work for me:
-I get the invalid session token all the time
-windows open in the same tab as initiated from

Can I revert the update to older version (like 0.10) somehow?

**Comment by wahoobie** [comment]
I think this is because of Salesforce now enforcing TLS 1.1 vs. the old 1.0 - can you look into this?  That's why this plug-in still works in PROD but none of or SANDBOX instances.

**Comment by jesperkristensen** [comment]
These are two separate issues:

Re. invalid session token: It is Chrome making the request no matter if you use Salesforce directly or through the Inspector, so it cannot be TLS 1.1 vs 1.0. It works fine for me in sandboxes and production. Do you have any special Cookie settings in your Chrome?

I changed links to open in the same tab by default, so that you can now use all your browser's commands for opening links including holding the Ctrl key down, or right clicking and selecting "Open link in new tab" and "Open link in new window". I realize this is a rather big change, but it worked a lot better for me after a few days of getting used to, and I hope it will be the same for most users.

**Comment by wahoobie** [comment]
A new permission prompt and chance re-enable the extension occurred tonight and it's working again. Odd as I just accepted the prompt with the 1.0 update....but hey it's working again.  Thank you!

**Comment by jesperkristensen** [comment]
I am closing this since I didn't receive any further actionable information. We can reopen if any new useful information arrives.
