### ISSUE TITLE
Chrome becomes unresponsive after using View All Data

### ISSUE THREAD

**Issue by JodieM** [sorenkrabbe/Chrome-Salesforce-inspector#93]
Just being experiencing this lately. 
Running Chrome 52.0x. or 53.0.x (on two different computers, both running latest Windows 10, but both on the same network). After using the view all data screen, then the Salesforce tab becomes unresponsive and the Kill / Wait window pops up. 

The first sign of something being wrong is double clicking on a field does not make it editable. 

Sorry for being so vague, and I will try to add more to the issue if I find anything more helpful, but I thought it was worthwhile logging in case anyone else is experiencing the issue.

**Comment by jesperkristensen** [comment]
Does it happen on specific objects, and how many fields and relations do they have? I have seen it become unresponsive for a short period and then eventually recover on the Organization object, because it has a lot of fields, and on the User object, because it has a lot of relations (The CreatedBy and LastModifiedBy relations)

**Comment by jesperkristensen** [comment]
No response, closing.
