### ISSUE TITLE
Error pasting excel table (from clipboard) with Chrome on mac, works with Firefox

### ISSUE THREAD

**Issue by dibe84** [sorenkrabbe/Chrome-Salesforce-inspector#94]
Hello, 
I'm using this plugin with mac, it works perfectly with Firefox and almost perfectly with Chrome.
With Chrome the "import" doesn't work: when I paste an Excel table it always return  "Error: No records to import". Pasting the same table with Firefox works.

I know the two plugins (Chrome and Firefox) are from different develoers but they seem to be exactly the same. Maybe somebody can help me to make it work with Chrome as well?

**Comment by jesperkristensen** [comment]
Are you using the same version in both Chrome and Firefox? (the version number should be printed in  the bottom of the menu.)

**Comment by dibe84** [comment]
Hello! Thanks for checking my issue. Yes, in both browsers I'm using version 1.0.

another details: if I paste table from openoffice (always with OSX) works in chrome!

**Comment by jesperkristensen** [comment]
Strange. I don't have a Mac to test myself, so can you try this test?

Copy this address into Chrome's address bar:

data:text/html,%3Ctextarea%20onpaste=%22this.value='::'+btoa(event.clipboardData.getData('text/plain'));return%20false%22%3E%3C/textarea%3E

Copy/paste some data from Excel into the text box that appears in chrome.

Copy/paste the data that appears in the text box into this issue.

**Comment by dibe84** [comment]
Hello, this is what I obtain copying the table from excel:

::aWQNYQ1iDWM=

This is the original table:

![image](https://cloud.githubusercontent.com/assets/2447890/18846455/45dd8ce0-8426-11e6-8254-18a228456089.png)


Tomorrow morning I'll copy what I obtain from openoffice.

**Comment by jesperkristensen** [comment]
Ok, I can see what the problem is.

What you pasted decodes as "id\ra\rb\rc"

Which means that the line breaks are written as CR, whereas the code in Salesforce Inspector can only parse CRLF and LF. The code cannot detect the line breaks and interprets it all as one single line.

What version of Excel and Mac OS are you using? My guess is that Excel writes line breaks the wrong way, and Firefox helpfully corrects the mistake, whereas Chrome just passes the incorrect data along. It is strange, since the last version of Mac OS using CR for line breaks was Mac OS 9, from 1999, which I am sure you are not using.

I am a little concerned if I fix your case I might break someone else's case. I will have to think a bit about it.

**Comment by dibe84** [comment]
now i'm from my personal mac and it has version 10.11.2, excel version 15.11.2.
Tomorrow i'll tell u the version of my professional mac but I guess they have the same version. 

I also tried with two collagues' macs and still same issue...

**Comment by jesperkristensen** [comment]
Ok, your mac version is quite new. I am not sure how Excel for Mac versions run, but I guess your Excel version is also relatively new.

I wonder how Excel can manage to get simple data formats wrong in so many ways :/

**Comment by dibe84** [comment]
do you know if there are mac users actually able to perform the import with chrome/excel?

**Comment by jesperkristensen** [comment]
This should now be fixed in the next release.

**Comment by dibegittest** [comment]
Nice to hear! In current version still doesn't work for me

**Comment by zwl1126** [comment]
The problem remains unresolved.
